{
  pkgs,
  inputs,
  ...
}:
let
  kenku = pkgs.callPackage ./kenku-fm.nix { inherit pkgs; };
in
{
  home.packages = with pkgs; [
    (python313.withPackages (
      p: with p; [
        pandas
        requests
      ]
    ))
    # winboat
    yt-dlp
    pandoc
    texliveFull
    rmpc
    kew
    claude-desktop
    inputs.zennotes.packages.${pkgs.system}.zennotes-desktop
    kenku
    claude-code
    sqlite
    _1password-cli
    vicinae
    go
    curl
    less
    nh
    ffmpeg_8-full
    poppler-utils
    prettyping
    redis
    tailscale
    gh
    tree
    delta
    magic-wormhole
    yazi-unwrapped
    pcmanfm
    xarchiver
    # gimp2-with-plugins
    ripgrep-all
    tableplus
    imagemagick
    pup
    gum
    font-awesome
    slack
    discord
    spotify
    lnav
    _1password-gui
    sqlite
    playerctl
    obsidian
    signal-desktop
    zellij
    distrobox
    cliphist
    ueberzugpp
    resvg
    imagemagick
    file
    cava
    libnotify
    smartmontools
    fluent-gtk-theme
    fluent-icon-theme
    candy-icons
    audacious
    rustdesk-flutter
    inkscape-with-extensions
    scribus
    sushi
    cheese
    swaynotificationcenter
    pavucontrol
    cmus
    qobuz-player
    dconf
    streamdeck-ui
    libsecret
    pulseaudio
    wezterm
    chromium
    ghostty
    termusic
    wf-recorder
    openrgb-with-all-plugins
    wget
    wlogout
    postman
    syncthing
    gnome-connections
    unzip
    alacritty
    fuzzel
    vial
    via
    ollama-vulkan
    inotify-tools
    protonup-qt
    proton-vpn
    dig
    openssl
    r2modman
    spotatui
    _7zip-zstd-rar
    fastfetch
    firefoxpwa
    rembg
    nautilus
    yubioath-flutter
    nodejs
    devenv
  ];
}
