{ pkgs, inputs, ... }:
{
  home.packages = with pkgs; [
    (python313.withPackages (
      p: with p; [
        pandas
        requests
      ]
    ))
    sqlite
    _1password-cli
    vicinae
    go
    curl
    less
    nh
    ffmpeg_8-full
    poppler
    prettyping
    redis
    tailscale
    gh
    tree
    delta
    magic-wormhole
    yazi-unwrapped
    pcmanfm
    xarchiver
    gimp2-with-plugins
    ripgrep-all
    tableplus
    imagemagick
    pup
    gum
    font-awesome
    slack
    discord
    spotify
    lnav
    _1password-gui
    sqlite
    playerctl
    obsidian
    signal-desktop
    zellij
    magnetic-catppuccin-gtk
    distrobox
    cliphist
    ueberzugpp
    resvg
    imagemagick
    file
    cava
    libnotify
    smartmontools
    fluent-gtk-theme
    fluent-icon-theme
    audacious
    rustdesk-flutter
    inkscape-with-extensions
    scribus
    sushi
    cheese
    swaynotificationcenter
    pavucontrol
    cmus
    qobuz-player
    dconf
    streamdeck-ui
    libsecret
    pulseaudio
    wezterm
    chromium
    ghostty
    termusic
    wf-recorder
    openrgb-with-all-plugins
    wget
    wlogout
    postman
    syncthing
    realvnc-vnc-viewer
    unzip
    alacritty
    fuzzel
    vial
    via
    supersonic-wayland
    ollama-vulkan
    inotify-tools
    protonup-qt
    r2modman
  ];
}
